/** Shared with loan application page and POST /api/loan-application — keep in sync. */

export const REQUIRED_FIELDS = [
  "firstName",
  "lastName",
  "email",
  "phone",
  "streetAddress",
  "city",
  "stateRegion",
  "postalCode",
  "monthsAtAddress",
  "dob",
  "gender",
  "maritalStatus",
  "dependants",
  "employer",
  "monthsWithEmployer",
  "jobTitle",
  "incomeType",
  "salaryAfterTax",
  "salaryFrequency",
  "visaType",
  "livingCondition",
  "rentMortgagePayment",
  "paymentFrequency",
  "monthlyExpenses",
  "loanType",
  "loanAmount",
  "incomeExpenseChanges",
  "consentMarketing",
  "consentDataProcessing",
];

export const initialData = {
  firstName: "",
  middleName: "",
  lastName: "",
  email: "",
  countryCode: "+64",
  phone: "",
  streetAddress: "",
  city: "",
  stateRegion: "",
  countryRegionCode: "New Zealand",
  postalCode: "",
  monthsAtAddress: "",
  dob: "",
  gender: "",
  maritalStatus: "",
  dependants: "",
  referenceName: "",
  referencePhone: "",
  employer: "",
  monthsWithEmployer: "",
  jobTitle: "",
  incomeType: "",
  salaryAfterTax: "",
  salaryFrequency: "",
  visaType: "",
  livingCondition: "Renting",
  rentMortgagePayment: "",
  paymentFrequency: "Weekly",
  monthlyExpenses: "",
  loanType: "",
  loanAmount: "",
  incomeExpenseChanges: "",
  consentMarketing: false,
  consentDataProcessing: false,
};

export const LOAN_FORM_FIELD_ORDER = Object.keys(initialData);
